# -*- coding: utf-8 -*-
# currencies.py - 60+ world currencies with dynamic exchange rates to USD (no emojis)

CURRENCIES = {
    "USD": {"symbol": "$", "name": "US Dollar", "usd_multiplier": 1.0},
    "EUR": {"symbol": "€", "name": "Euro", "usd_multiplier": 0.92},
    "GBP": {"symbol": "£", "name": "British Pound", "usd_multiplier": 0.79},
    "INR": {"symbol": "₹", "name": "Indian Rupee", "usd_multiplier": 83.5},
    "JPY": {"symbol": "¥", "name": "Japanese Yen", "usd_multiplier": 155.0},
    "CNY": {"symbol": "¥", "name": "Chinese Yuan", "usd_multiplier": 7.25},
    "AED": {"symbol": "AED", "name": "UAE Dirham", "usd_multiplier": 3.67},
    "SAR": {"symbol": "SR", "name": "Saudi Riyal", "usd_multiplier": 3.75},
    "BRL": {"symbol": "R$", "name": "Brazilian Real", "usd_multiplier": 5.15},
    "CAD": {"symbol": "C$", "name": "Canadian Dollar", "usd_multiplier": 1.36},
    "AUD": {"symbol": "A$", "name": "Australian Dollar", "usd_multiplier": 1.50},
    "CHF": {"symbol": "CHF", "name": "Swiss Franc", "usd_multiplier": 0.90},
    "MXN": {"symbol": "Mex$", "name": "Mexican Peso", "usd_multiplier": 16.70},
    "KRW": {"symbol": "₩", "name": "South Korean Won", "usd_multiplier": 1360.0},
    "SGD": {"symbol": "S$", "name": "Singapore Dollar", "usd_multiplier": 1.35},
    "HKD": {"symbol": "HK$", "name": "Hong Kong Dollar", "usd_multiplier": 7.80},
    "NZD": {"symbol": "NZ$", "name": "New Zealand Dollar", "usd_multiplier": 1.63},
    "ZAR": {"symbol": "R", "name": "South African Rand", "usd_multiplier": 18.40},
    "NGN": {"symbol": "₦", "name": "Nigerian Naira", "usd_multiplier": 1450.0},
    "EGP": {"symbol": "E£", "name": "Egyptian Pound", "usd_multiplier": 47.0},
    "PKR": {"symbol": "Rs", "name": "Pakistani Rupee", "usd_multiplier": 278.0},
    "BDT": {"symbol": "৳", "name": "Bangladeshi Taka", "usd_multiplier": 117.0},
    "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah", "usd_multiplier": 16000.0},
    "PHP": {"symbol": "₱", "name": "Philippine Peso", "usd_multiplier": 58.0},
    "THB": {"symbol": "฿", "name": "Thai Baht", "usd_multiplier": 36.5},
    "VND": {"symbol": "₫", "name": "Vietnamese Dong", "usd_multiplier": 25400.0},
    "MYR": {"symbol": "RM", "name": "Malaysian Ringgit", "usd_multiplier": 4.70},
    "TRY": {"symbol": "₺", "name": "Turkish Lira", "usd_multiplier": 32.20},
    "PLN": {"symbol": "zł", "name": "Polish Zloty", "usd_multiplier": 3.95},
    "UAH": {"symbol": "₴", "name": "Ukrainian Hryvnia", "usd_multiplier": 40.0},
    "SEK": {"symbol": "kr", "name": "Swedish Krona", "usd_multiplier": 10.70},
    "NOK": {"symbol": "kr", "name": "Norwegian Krone", "usd_multiplier": 10.60},
    "DKK": {"symbol": "kr", "name": "Danish Krone", "usd_multiplier": 6.90},
    "CZK": {"symbol": "Kč", "name": "Czech Koruna", "usd_multiplier": 22.80},
    "HUF": {"symbol": "Ft", "name": "Hungarian Forint", "usd_multiplier": 360.0},
    "RON": {"symbol": "lei", "name": "Romanian Leu", "usd_multiplier": 4.60},
    "ILS": {"symbol": "₪", "name": "Israeli Shekel", "usd_multiplier": 3.70},
    "KES": {"symbol": "KSh", "name": "Kenyan Shilling", "usd_multiplier": 130.0},
    "GHS": {"symbol": "GH₵", "name": "Ghanaian Cedi", "usd_multiplier": 14.50},
    "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling", "usd_multiplier": 2600.0},
    "UGX": {"symbol": "USh", "name": "Ugandan Shilling", "usd_multiplier": 3800.0},
    "ETB": {"symbol": "Br", "name": "Ethiopian Birr", "usd_multiplier": 57.0},
    "XOF": {"symbol": "CFA", "name": "West African CFA Franc", "usd_multiplier": 605.0},
    "MAD": {"symbol": "DH", "name": "Moroccan Dirham", "usd_multiplier": 10.0},
    "DZD": {"symbol": "DA", "name": "Algerian Dinar", "usd_multiplier": 134.0},
    "QAR": {"symbol": "QR", "name": "Qatari Riyal", "usd_multiplier": 3.64},
    "KWD": {"symbol": "KD", "name": "Kuwaiti Dinar", "usd_multiplier": 0.31},
    "BHD": {"symbol": "BD", "name": "Bahraini Dinar", "usd_multiplier": 0.38},
    "OMR": {"symbol": "RO", "name": "Omani Rial", "usd_multiplier": 0.38},
    "JOD": {"symbol": "JD", "name": "Jordanian Dinar", "usd_multiplier": 0.71},
    "LBP": {"symbol": "L£", "name": "Lebanese Pound", "usd_multiplier": 89500.0},
    "IRR": {"symbol": "RL", "name": "Iranian Rial", "usd_multiplier": 42000.0},
    "IQD": {"symbol": "IQD", "name": "Iraqi Dinar", "usd_multiplier": 1310.0},
    "AFN": {"symbol": "Af", "name": "Afghan Afghani", "usd_multiplier": 70.0},
    "NPR": {"symbol": "Rs", "name": "Nepalese Rupee", "usd_multiplier": 133.0},
    "LKR": {"symbol": "SLRs", "name": "Sri Lankan Rupee", "usd_multiplier": 300.0},
    "MMK": {"symbol": "K", "name": "Myanmar Kyat", "usd_multiplier": 2100.0},
    "KHR": {"symbol": "CR", "name": "Cambodian Riel", "usd_multiplier": 4100.0},
    "TWD": {"symbol": "NT$", "name": "New Taiwan Dollar", "usd_multiplier": 32.30},
    "CLP": {"symbol": "CLP$", "name": "Chilean Peso", "usd_multiplier": 920.0},
    "ARS": {"symbol": "Arg$", "name": "Argentine Peso", "usd_multiplier": 890.0},
    "COP": {"symbol": "Col$", "name": "Colombian Peso", "usd_multiplier": 3850.0},
    "PEN": {"symbol": "S/.", "name": "Peruvian Sol", "usd_multiplier": 3.72},
    "VES": {"symbol": "Bs.D", "name": "Venezuelan Bolivar", "usd_multiplier": 36.50}
}
